/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/Car.gltf
*/

import React from "react";
import { useGLTF } from "@react-three/drei";
import { useCustomization } from "./Context/Customization";
import * as THREE from "three";

const Car = (props) => {
  const { nodes, materials } = useGLTF("/Models/Car.gltf");

  const { carColor } = useCustomization();

  //create a Black metallic color with THREE
  const blackMetallic = new THREE.Color(0x000000);

  //create a Blue metallic color with THREE
  const blueMetallic = new THREE.Color("#ADD8E6");

  //create a Red metallic color with THREE
  const redMetallic = new THREE.Color(0xff0000);

  //create a White metallic color with THREE
  const whiteMetallic = new THREE.Color(0xffffff);

  //create a Yellow metallic color with THREE
  const yellowMetallic = new THREE.Color(0xffff00);

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cube007.geometry}
        material={materials["Leather ornaments"]}
      />
      <mesh
        geometry={nodes.Cube007_1.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh geometry={nodes.Cube007_2.geometry}>
        <meshStandardMaterial
          attach="material"
          color={
            carColor === "Black"
              ? blackMetallic
              : carColor === "Blue"
              ? blueMetallic
              : carColor === "Red"
              ? redMetallic
              : carColor === "White"
              ? whiteMetallic
              : carColor === "Yellow"
              ? yellowMetallic
              : blackMetallic
          }
          metalness={1}
          roughness={0.1}
        />
      </mesh>
      <mesh
        geometry={nodes.Cube007_3.geometry}
        material={materials["Brazilian wood - Peroba Mica"]}
      />
      <mesh
        geometry={nodes.Cube007_4.geometry}
        material={materials["Car windshield glass"]}
      />
      <mesh
        geometry={nodes.Cube007_5.geometry}
        material={materials["Car plastic dark"]}
      />
      <mesh
        geometry={nodes.Cube007_6.geometry}
        material={materials["Carlight shingle chrome red"]}
      />
      <mesh
        geometry={nodes.Cube007_7.geometry}
        material={materials["Carlight shingle chrome orange"]}
      />
      <mesh geometry={nodes.Cube007_8.geometry} material={materials.Mirror} />
      <mesh
        geometry={nodes.Cube007_9.geometry}
        material={materials["Car leather red"]}
      />
      <mesh
        geometry={nodes.Cube007_10.geometry}
        material={materials["Car rubber wheel"]}
      />
      <mesh
        geometry={nodes.Cube007_11.geometry}
        material={materials["Rusted steel"]}
      />
      <mesh
        geometry={nodes.Cube013.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh geometry={nodes.Cube013_1.geometry} material={materials.FUEL} />
      <mesh
        geometry={nodes.Cube013_2.geometry}
        material={materials["FUEL CLOCK"]}
      />
      <mesh
        geometry={nodes.Cube013_3.geometry}
        material={materials["FUEL OIL"]}
      />
      <mesh
        geometry={nodes.Cube013_4.geometry}
        material={materials["FUEL 80"]}
      />
      <mesh
        geometry={nodes.Cube013_5.geometry}
        material={materials["Car windshield glass"]}
      />
      <mesh
        geometry={nodes.Cube013_6.geometry}
        material={materials["Plastic Shader"]}
      />
      <mesh
        geometry={nodes.Cube013_7.geometry}
        material={materials["Black Plastic"]}
      />
      <mesh
        geometry={nodes.Cube013_8.geometry}
        material={materials["Car plastic dark"]}
      />
      <mesh
        geometry={nodes.Cube013_9.geometry}
        material={materials["Car paint"]}
      />
      <mesh
        geometry={nodes.Cube013_10.geometry}
        material={materials["Car rubber wheel"]}
      />
      <mesh
        geometry={nodes.Cube013_11.geometry}
        material={materials["Rusted steel"]}
      />
      <mesh
        geometry={nodes.Plane005.geometry}
        material={materials["Car rubber wheel"]}
      />
      <mesh
        geometry={nodes.Plane005_1.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)"].geometry}
        material={materials["MG_Cars_(logo)"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_1"].geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_2"].geometry}
        material={materials["Car plastic dark"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_3"].geometry}
        material={materials["Car paint"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_4"].geometry}
        material={materials.Sensore}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_5"].geometry}
        material={materials["Car windshield glass"]}
      />
      <mesh
        geometry={nodes["MG_Cars_(logo)_6"].geometry}
        material={materials.Speedometer}
      />
      <mesh
        geometry={nodes.Cube026.geometry}
        material={materials["Old Metal Pan"]}
      />
      <mesh
        geometry={nodes.Cube026_1.geometry}
        material={materials["Car paint"]}
      />
      <mesh
        geometry={nodes.Cube026_2.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Car rubber wheel"]}
      />
      <mesh
        geometry={nodes.Plane_1.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh
        geometry={nodes.Cube003.geometry}
        material={materials["Stainless Steel Clean"]}
      />
      <mesh
        geometry={nodes.Cube003_1.geometry}
        material={materials["Car rubber wheel"]}
      />
      <mesh
        geometry={nodes.Cube003_2.geometry}
        material={materials["Black Plastic"]}
      />
      <mesh
        geometry={nodes.Cube003_3.geometry}
        material={materials["Car windshield glass"]}
      />
    </group>
  );
};

export default Car;

useGLTF.preload("/Models/Car.gltf");
