/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/Models/retro_car.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useCustomization } from './Context/Customization'
import * as THREE from 'three'

const Retro = (props) => {
  const { nodes, materials } = useGLTF('/Models/retro_car.glb')
  const { carColor } = useCustomization();

  //create a Black metallic color with THREE
  const blackMetallic = new THREE.Color(0x000000);

  //create a Blue metallic color with THREE
  const blueMetallic = new THREE.Color("#ADD8E6");

  //create a Red metallic color with THREE
  const redMetallic = new THREE.Color(0xff0000);

  //create a White metallic color with THREE
  const whiteMetallic = new THREE.Color(0xffffff);

  //create a Yellow metallic color with THREE
  const yellowMetallic = new THREE.Color(0xffff00);
  return (
    <group {...props} dispose={null} position={[0, -1, 0]}>
      <group position={[0, 0.99, 0]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Back1_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Back2_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Back3_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Body1_low_Lincoln3_0.geometry}>
          <meshStandardMaterial
          attach="material"
          color={
            carColor === "Black"
              ? blackMetallic
              : carColor === "Blue"
              ? blueMetallic
              : carColor === "Red"
              ? redMetallic
              : carColor === "White"
              ? whiteMetallic
              : carColor === "Yellow"
              ? yellowMetallic
              : blackMetallic
          }
          metalness={1}
          roughness={0.1}
        />
          </mesh>
          <mesh geometry={nodes.Body3_low_Lincoln3_0.geometry} material={materials.Lincoln3} />
          <mesh geometry={nodes.Fars_Fars2_0.geometry} material={materials.Fars2} />
          <mesh geometry={nodes.Fars1_Fars3_0.geometry} material={materials.Fars3} />
          <mesh geometry={nodes.Foundation1_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Foundation2_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Foundation3_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Foundation4_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Foundation5_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Front1_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Front2_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Front3_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Front4_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Front5_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Glass_back1_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Glass_back2_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Glass_back3_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Indicators_Ind_0.geometry} material={materials.material} />
          <mesh geometry={nodes.Indicators1_Ind1_0.geometry} material={materials.Ind1} />
          <mesh geometry={nodes.Mirrors_Roof_Mirr_0.geometry} material={materials.Mirr} />
          <mesh geometry={nodes.Mirrors_Wheels_Mirr_Wheels_0.geometry} material={materials.Mirr_Wheels} />
          <mesh geometry={nodes.Roof1_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Roof2_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Roof3_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Roof4_low_Lincoln1_0.geometry} material={materials.Lincoln1} />
          <mesh geometry={nodes.Salon1_low_Lincoln3_0.geometry} material={materials.Lincoln3} />
          <mesh geometry={nodes.Salon2_low_Lincoln3_0.geometry} material={materials.Lincoln3} />
          <mesh geometry={nodes.Salon3_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Wheel_1_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.detailes_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.strap_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.straps_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.tire_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Wheel_3_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Wheel_4_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.detailes_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.strap_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.straps_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.tire_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Wheel_6_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0001.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0002.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0002.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0003.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0003.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0004.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0004.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.center_low_Lincoln2_0005.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.needles_low_Lincoln2_0005.geometry} material={materials.Lincoln2} />
          <mesh geometry={nodes.Window_Back_Glasses_0.geometry} material={materials.Glasses} />
          <mesh geometry={nodes.Window_Back1_Glasses1_0.geometry} material={materials.Glasses1} />
          <mesh geometry={nodes.Window_Roof_Glasses_0.geometry} material={materials.Glasses} />
          <mesh geometry={nodes.Window_Roof1_Glasses1_0.geometry} material={materials.Glasses1} />
        </group>
      </group>
    </group>
  )
}

export default Retro

useGLTF.preload('/Models/retro_car.glb')
